// 湘南工科大学 シラバスデータ
// ナンバリング（授業コード）、科目名、必選区分（必修/選択必修/選択）

const SYLLABUS_COURSES = [
  // 共通基盤ワークショップ1A
  { code: "B30A01A1", name: "共通基盤ワークショップ１Ａ　～「豊かさ」とは何だろう？～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01B1", name: "共通基盤ワークショップ１Ａ　～ＳＤＧｓから世界の問題を見つめてみよう～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01C1", name: "共通基盤ワークショップ１Ａ　～スポーツを創造しよう～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01D1", name: "共通基盤ワークショップ１Ａ　～マインドスポーツ（テーブルゲーム）の考案～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01E1", name: "共通基盤ワークショップ１Ａ　～中小企業について考えてみよう～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01F1", name: "共通基盤ワークショップ１Ａ　～対人関係とコミュニケーション～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01G1", name: "共通基盤ワークショップ１Ａ　～音楽文化の歴史と未来～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01H1", name: "共通基盤ワークショップ１Ａ　～自分らしくを楽しめるセルフプロデュース～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01J1", name: "共通基盤ワークショップ１Ａ　～考える力（思考力・決断力）を科学する～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01K1", name: "共通基盤ワークショップ１Ａ　～社会問題を解決に導く工学とは～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01L1", name: "共通基盤ワークショップ１Ａ　～科学技術について考えてみよう～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01M1", name: "共通基盤ワークショップ１Ａ　～ＡＩを使い倒してみる～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01N1", name: "共通基盤ワークショップ１Ａ　～未来の湘南工科大学をみんなで創ろう～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01P1", name: "共通基盤ワークショップ１Ａ　～シミュレーションで身近な社会課題を解決～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01Q1", name: "共通基盤ワークショップ１Ａ　～湘南地域とデザイン～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },
  { code: "B30A01R1", name: "共通基盤ワークショップ１Ａ　～プラスチックについて学ぶ～", type: "selective_required", grade: [1], semester: ["1"], group: "workshop_1a" },


  // 共通基盤ワークショップ1B
  { code: "B30A02A1", name: "共通基盤ワークショップ１Ｂ　～「豊かさ」とは何だろう？～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02B1", name: "共通基盤ワークショップ１Ｂ　～ＳＤＧｓから世界の問題を見つめてみよう～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02C1", name: "共通基盤ワークショップ１Ｂ　～スポーツを創造しよう～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02D1", name: "共通基盤ワークショップ１Ｂ　～マインドスポーツ（テーブルゲーム）の考案～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02E1", name: "共通基盤ワークショップ１Ｂ　～中小企業について考えてみよう～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02F1", name: "共通基盤ワークショップ１Ｂ　～対人関係とコミュニケーション～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02G1", name: "共通基盤ワークショップ１Ｂ　～音楽文化の歴史と未来～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02H1", name: "共通基盤ワークショップ１Ｂ　～自分らしくを楽しめるセルフプロデュース～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02J1", name: "共通基盤ワークショップ１Ｂ　～考える力（思考力・決断力）を科学する～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02K1", name: "共通基盤ワークショップ１Ｂ　～社会問題を解決に導く工学とは～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02L1", name: "共通基盤ワークショップ１Ｂ　～科学技術について考えてみよう～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02M1", name: "共通基盤ワークショップ１Ｂ　～ＡＩを使い倒してみる～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02N1", name: "共通基盤ワークショップ１Ｂ　～未来の湘南工科大学をみんなで創ろう～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02P1", name: "共通基盤ワークショップ１Ｂ　～シミュレーションで身近な社会課題を解決～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02Q1", name: "共通基盤ワークショップ１Ｂ　～湘南地域とデザイン～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },
  { code: "B30A02R1", name: "共通基盤ワークショップ１Ｂ　～プラスチックについて学ぶ～", type: "selective_required", grade: [1], semester: ["2"], group: "workshop_1b" },

  // 共通基盤ワークショップ2A
  { code: "B30B01A2", name: "共通基盤ワークショップ２Ａ　～アイデア活用演習プロジェクト～", type: "required" },
  { code: "B30B01B2", name: "共通基盤ワークショップ２Ａ　～デザイン思考＠基礎プロジェクト～", type: "required" },
  { code: "B30B01C2", name: "共通基盤ワークショップ２Ａ　～アイデアの作り方プロジェクト～", type: "required" },
  { code: "B30B01D2", name: "共通基盤ワークショップ２Ａ　～機械創造設計製作プロジェクト～", type: "required" },
  { code: "B30B01E2", name: "共通基盤ワークショップ２Ａ　～キャリアデザインプロジェクト～", type: "required" },
  { code: "B30B01F2", name: "共通基盤ワークショップ２Ａ　～アイデア発想プロジェクト～", type: "required" },
  { code: "B30B01G2", name: "共通基盤ワークショップ２Ａ　～IoTファブレスへの挑戦プロジェクト(a)～", type: "required" },
  { code: "B30B01H2", name: "共通基盤ワークショップ２Ａ　～社会人基礎力プロジェクト(a)～", type: "required" },
  { code: "B30B01J2", name: "共通基盤ワークショップ２Ａ　～プリント回路基盤開発プロジェクト～", type: "required" },
  { code: "B30B01K2", name: "共通基盤ワークショップ２Ａ　～生成AIを活用した課題解決プロジェクト～", type: "required" },
  { code: "B30B01L2", name: "共通基盤ワークショップ２Ａ　～新しい数学授業を提案するプロジェクト～", type: "required" },
  { code: "B30B01M2", name: "共通基盤ワークショップ２Ａ　～Webサイト制作プロジェクト～", type: "required" },
  { code: "B30B01N2", name: "共通基盤ワークショップ２Ａ　～IoTファブレスへの挑戦プロジェクト(b)～", type: "required" },
  { code: "B30B01P2", name: "共通基盤ワークショップ２Ａ　～サイエンス教室資料作成プロジェクト～", type: "required" },
  { code: "B30B01Q2", name: "共通基盤ワークショップ２Ａ　～３Ｄゲーム制作プロジェクト～", type: "required" },
  { code: "B30B01R2", name: "共通基盤ワークショップ２Ａ　～プレゼンデザインプロジェクト～", type: "required" },
  { code: "B30B01S2", name: "共通基盤ワークショップ２Ａ　～地域デザインプロジェクト～", type: "required" },
  { code: "B30B01T2", name: "共通基盤ワークショップ２Ａ　～人生目標設定プロジェクト～", type: "required" },
  { code: "B30B01U2", name: "共通基盤ワークショップ２Ａ　～スポーツデータサイエンスプロジェクト～", type: "required" },
  { code: "B30B01V2", name: "共通基盤ワークショップ２Ａ　～ことばの分析プロジェクト～", type: "required" },

  // 共通基盤ワークショップ2B
  { code: "B30B02A2", name: "共通基盤ワークショップ２Ｂ　～ITエンジニアの就活準備プロジェクト～", type: "required" },

  // 修学基礎関連
  { code: "Av101Tce", name: "修学基礎", type: "required" },
  { code: "Av101Tce", name: "修学基礎（再）", type: "required" },
  { code: "Av201Sab", name: "キャリア形成", type: "required" },
  { code: "Av301Sce", name: "進路研究", type: "required" },

  // 技術者関連
  { code: "Av102Sbg", name: "技術者倫理", type: "elective" },
  { code: "Av103Ieh", name: "文章作成法", type: "elective" },

  // 学科横断プログラム
  { code: "Av202Sag", name: "学科横断プログラム２Ａ　～ＡＩコース～", type: "elective" },
  { code: "Av202Sag", name: "学科横断プログラム２Ａ　～ＩｏＴコース～", type: "elective" },
  { code: "Av202Sag", name: "学科横断プログラム２Ａ　～ロボティクスコース～", type: "elective" },
  { code: "Av202Sag", name: "学科横断プログラム２Ａ　～ＸＲメディアコース～", type: "elective" },
  { code: "Av202Sag", name: "学科横断プログラム２Ａ　～医工学コース～", type: "elective" },
  { code: "Av203Sbg", name: "学科横断プログラム２Ｂ　～ＡＩコース～", type: "elective" },
  { code: "Av203Sbg", name: "学科横断プログラム２Ｂ　～ＩｏＴコース～", type: "elective" },
  { code: "Av203Sbg", name: "学科横断プログラム２Ｂ　～ロボティクスコース～", type: "elective" },
  { code: "Av203Sbg", name: "学科横断プログラム２Ｂ　～ＸＲメディアコース～", type: "elective" },
  { code: "Av203Sbg", name: "学科横断プログラム２Ｂ　～医工学コース～", type: "elective" },
  { code: "Av302Ich", name: "学科横断プログラム３Ａ　～ＡＩコース～", type: "elective" },
  { code: "Av302Ich", name: "学科横断プログラム３Ａ　～ＩｏＴコース～", type: "elective" },
  { code: "Av302Ich", name: "学科横断プログラム３Ａ　～ロボティクスコース～", type: "elective" },
  { code: "Av302Ich", name: "学科横断プログラム３Ａ　～ＸＲメディアコース～", type: "elective" },
  { code: "Av302Ich", name: "学科横断プログラム３Ａ　～医工学コース～", type: "elective" },
  { code: "Av303Idh", name: "学科横断プログラム３Ｂ　～ＡＩコース～", type: "elective" },
  { code: "Av303Idh", name: "学科横断プログラム３Ｂ　～ＩｏＴコース～", type: "elective" },
  { code: "Av303Idh", name: "学科横断プログラム３Ｂ　～ロボティクスコース～", type: "elective" },
  { code: "Av303Idh", name: "学科横断プログラム３Ｂ　～ＸＲメディアコース～", type: "elective" },
  { code: "Av303Idh", name: "学科横断プログラム３Ｂ　～医工学コース～", type: "elective" },

  // 社会貢献
  { code: "Av104Sab", name: "社会貢献活動概論", type: "elective" },
  { code: "Av105Tdf", name: "社会貢献活動１", type: "elective" },
  { code: "Av204Tdf", name: "社会貢献活動２", type: "elective" },
  { code: "Av205Sab", name: "インターンシップ１", type: "elective" },
  { code: "Av304Sab", name: "インターンシップ２", type: "elective" },
  { code: "Av106Icd", name: "プロジェクト実習Ａ　～教職介護等体験～", type: "elective" },
  { code: "Av106Icd", name: "プロジェクト実習Ａ　～キャリアプランの作り方（入門編）～", type: "elective" },
  { code: "Av107Icd", name: "プロジェクト実習Ｂ　～教職介護等体験～", type: "elective" },
  { code: "Av107Icd", name: "プロジェクト実習Ｂ　～キャリアプランの作り方（入門編）～", type: "elective" },
  { code: "Av107Icd", name: "プロジェクト実習Ｂ　～図書館ボランティア～", type: "elective" },

  // 社会連携講座
  { code: "Av108Sab", name: "社会連携講座（１）～いろいろな関数～", type: "elective" },
  { code: "Av109Sab", name: "社会連携講座（２）～幾何学から学ぶ～", type: "elective" },
  { code: "Av110Sab", name: "社会連携講座（３）～統計学入門～", type: "elective" },
  { code: "Av111Sab", name: "社会連携講座（４）～教育産業概論～", type: "elective" },
  { code: "Av112Sab", name: "社会連携講座（５）～医療入門～", type: "elective" },
  { code: "Av113Sab", name: "社会連携講座（６）～思考のブラッシュアップ～", type: "elective" },

  // 教養科目
  { code: "As101Sae", name: "哲学をもつ", type: "elective" },
  { code: "As102Sae", name: "心理をよむ", type: "elective" },
  { code: "As103Sae", name: "文化をはぐくむ", type: "elective" },
  { code: "As104Sae", name: "歴史をみつめる", type: "elective" },
  { code: "As105Sae", name: "物語をつくる", type: "elective" },

  // 社会関連科目
  { code: "As201Iab", name: "くらしと法", type: "elective-required" },
  { code: "As202Iab", name: "政治行動", type: "elective-required" },
  { code: "As203Iab", name: "日本国憲法", type: "elective-required" },
  { code: "As301Ibd", name: "国際政治経済", type: "elective-required" },
  { code: "As302Ibd", name: "外交と安全保障", type: "elective-required" },
  { code: "As303Ibd", name: "グローバルデータ分析", type: "elective-required" },
  { code: "As304Ibd", name: "市場と経済", type: "elective-required" },
  { code: "As305Ibd", name: "企業経営", type: "elective-required" },
  { code: "As306Ibd", name: "会計と財務", type: "elective-required" },

  // 英語科目
  { code: "Ag101Icg", name: "英語リテラシー１", type: "required" },
  { code: "Ag102Icg", name: "英語リテラシー２", type: "required" },
  { code: "Ag201Iac", name: "英語コミュニケーション１", type: "required" },
  { code: "Ag202Iac", name: "英語コミュニケーション２", type: "required" },
  { code: "B30G01A1", name: "英語総合基礎(木3-1)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G01B1", name: "英語総合基礎(木3-2)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G01C1", name: "英語総合基礎(木3-3)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G01E1", name: "英語総合基礎(木3-4)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G01D1", name: "英語総合基礎(木4-1)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G01F1", name: "英語総合基礎(木4-2)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G01G1", name: "英語総合基礎(木4-3)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G01H1", name: "英語総合基礎(木4-4)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G02A1", name: "英語総合発展(木3-1)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G02B1", name: "英語総合発展(木3-2)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G02C1", name: "英語総合発展(木3-3)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G02D1", name: "英語総合発展(木3-4)", period: 3, day: "thu", type: "elective-required" },
  { code: "B30G02E1", name: "英語総合発展(木4-1)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G02F1", name: "英語総合発展(木4-2)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G02G1", name: "英語総合発展(木4-3)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G02H1", name: "英語総合発展(木4-4)", period: 4, day: "thu", type: "elective-required" },
  { code: "B30G04A1", name: "実用英語(前期)", type: "elective" },
  { code: "B30G04K1", name: "実用英語(後期)", type: "elective" },
  { code: "B30G07K2", name: "時事ビジネス英語", type: "elective" },
  { code: "B30G08A1", name: "中国文化言語(2限)(前期)", period: 2, day: "mon", type: "elective" },
  { code: "B30G08B1", name: "中国文化言語(3限)(前期)", type: "elective" },
  { code: "B30G08C1", name: "中国文化言語(4限)(前期)", type: "elective" },
  { code: "B30G08K1", name: "中国文化言語(2限)(後期)", type: "elective" },
  { code: "B30G08L1", name: "中国文化言語(3限)(後期)", type: "elective" },
  { code: "B30G08M1", name: "中国文化言語(4限)(後期)", type: "elective" },
  { code: "B30G09A1", name: "朝鮮文化言語(2限)(前期)", type: "elective" },
  { code: "B30G09B1", name: "朝鮮文化言語(3限)(前期)", type: "elective" },
  { code: "B30G09K1", name: "朝鮮文化言語(2限)(後期)", type: "elective" },
  { code: "B30G09L1", name: "朝鮮文化言語(3限)(後期)", type: "elective" },  
  { code: "B30G03A1", name: "入門英語(前期)", type: "elective" },
  { code: "B30G03K1", name: "入門英語(後期)", type: "elective" },
  { code: "B30G10A1", name: "ロシア文化言語(2限)(前期)", type: "elective" },
  { code: "B30G10B1", name: "ロシア文化言語(3限)(前期)", type: "elective" },
  { code: "B30G10C1", name: "ロシア文化言語(4限)(前期)", type: "elective" },
  { code: "B30G10K1", name: "ロシア文化言語(2限)(後期)", type: "elective" },
  { code: "B30G10L1", name: "ロシア文化言語(3限)(後期)", type: "elective" },
  { code: "B30G10M1", name: "ロシア文化言語(4限)(後期)", type: "elective" },  
  { code: "B30G13T2", name: "海外語学研修(前期)", type: "other" },
  { code: "B30G13V2", name: "海外語学研修(後期)", type: "other" },
  { code: "B30G11A1", name: "日本語Ａ", type: "elective" },
  { code: "B30G12K1", name: "日本語Ｂ", type: "elective" },

  // スポーツ科目
  { code: "B30H03A1", name: "スポーツを分析する(１限目)", type: "required" },
  { code: "B30H03B1", name: "スポーツを分析する(２限目)", type: "required" },
  { code: "B30H01A2", name: "スポーツで健康を科学する(水1-1)", type: "required" },
  { code: "B30H01B2", name: "スポーツで健康を科学する(水1-2)", type: "required" },
  { code: "B30H01C2", name: "スポーツで健康を科学する(水1-3)", type: "required" },
  { code: "B30H01D2", name: "スポーツで健康を科学する(水2-1)", type: "required" },
  { code: "B30H01E2", name: "スポーツで健康を科学する(水2-2)", type: "required" },
  { code: "B30H01F2", name: "スポーツで健康を科学する(水2-3)", type: "required" },
  { code: "B30H02A2", name: "スポーツで健康を科学する(木1-1)", type: "required" },
  { code: "B30H02B2", name: "スポーツで健康を科学する(木1-2)", type: "required" },
  { code: "B30H02C2", name: "スポーツで健康を科学する(木1-3)", type: "required" },
  { code: "B30H02D2", name: "スポーツで健康を科学する(木2-1)", type: "required" },
  { code: "B30H02E2", name: "スポーツで健康を科学する(木2-2)", type: "required" },
  { code: "B30H02F2", name: "スポーツで健康を科学する(木2-3)", type: "required" },
  { code: "B30H01A3", name: "スポーツで健康を科学する(再)(前期)", type: "required" },
  { code: "B30H02A3", name: "スポーツで健康を科学する(再)(後期)", type: "required" },
  { code: "B30H03A1", name: "生涯スポーツ論(前期)", type: "elective" },
  { code: "B30H03K2", name: "生涯スポーツ論(後期)", type: "elective" },
  { code: "B30H06U1", name: "シーズンスポーツ（サーフィン）", type: "other" },

  // コンピュータ関連
  { code: "B30I01A1", name: "コンピュータリテラシ基礎(メ)", type: "required" },
  { code: "B30I02K1", name: "コンピュータリテラシ応用(メ)", type: "required" },
  { code: "B30I03A2", name: "コンピュータリテラシ発展 ～pythonを学ぶ～", type: "elective" },
  { code: "B30I03B2", name: "コンピュータリテラシ発展 ～VBAを学ぶ～", type: "elective" },
  { code: "B30I04K2", name: "社会とコンピュータ", type: "elective" },
//  { code: "B30I04B1", name: "コンピュータのしくみ", type: "elective" },

  // 教職科目
  { code: "At101Sgh", name: "（教）教職入門", type: "required" },
  { code: "At102Igh", name: "（教）教育原理", type: "required" },
  { code: "At103Sgh", name: "（教）教育心理", type: "required" },
  { code: "At201Igh", name: "（教）特別支援教育", type: "required" },
  { code: "At104Igh", name: "（教）教育制度論", type: "required" },
  { code: "At202Igh", name: "（教）教育関係法規", type: "elective" },
  { code: "At203Igh", name: "（教）教育課程論", type: "required" },
  { code: "At204Sgh", name: "（教）工業科教育法１", type: "required" },
  { code: "At205Sgh", name: "（教）工業科教育法２", type: "required" },
  { code: "At208Sgh", name: "（教）数学科教育法１", type: "required" },
  { code: "At209Sgh", name: "（教）数学科教育法２", type: "required" },
  { code: "At210Igh", name: "（教）数学科教材研究１", type: "elective-required" },
  { code: "At211Igh", name: "（教）数学科教材研究２", type: "elective-required" },
  { code: "At212Sgh", name: "（教）技術科教育法１", type: "required" },
  { code: "At213Sgh", name: "（教）技術科教育法２", type: "required" },
  { code: "At214Igh", name: "（教）技術科教材研究１", type: "elective-required" },
  { code: "At215Igh", name: "（教）技術科教材研究２", type: "elective-required" },
  { code: "At216Sgh", name: "（教）道徳教育の指導法", type: "required" },
  { code: "At217Sgh", name: "（教）特別活動及び総合的な学習の指導法", type: "required" },
  { code: "At218Igh", name: "（教）生徒指導及び進路指導", type: "required" },
  { code: "At219Igh", name: "（教）教育相談", type: "required" },
  { code: "At301Igh", name: "（教）教育実習ゼミ１", type: "required" },
  { code: "At302Tgh", name: "（教）教育実習ゼミ２", type: "required" },
  { code: "At303Tgh", name: "（教）教育実習１", type: "required" },
  { code: "At304Tgh", name: "（教）教育実習２", type: "required" },
  { code: "At220Tgh", name: "（教）学校インターンシップ", type: "elective" },
  { code: "At305Sgh", name: "（教）教職実践演習（中・高）", type: "required" },
  { code: "At105Sgh", name: "（教）教育方法（ＩＣＴの活用を含む）", type: "required" },

  // 機械工学関連
  { code: "Mz101Sae", name: "エンジニアリング基礎", type: "required" },
  { code: "Mc101Tah", name: "工作実習１", type: "required" },
  { code: "Ma101Iah", name: "３次元ＣＡＤ", type: "required" },
  { code: "Ma102Ich", name: "基礎製図", type: "required" },
  { code: "Mc102Tch", name: "工作実習２", type: "required" },
  { code: "Mc103Iag", name: "材料科学１", type: "required" },
  { code: "Me101Sag", name: "工業数学・力学基礎", type: "elective" },
  { code: "Md101Sdg", name: "メカトロニクス入門", type: "elective" },
  { code: "Mf101Sbg", name: "機械工学入門", type: "elective" },
  { code: "Me101Sag", name: "流体・工業熱力学基礎", type: "elective-required" },
  { code: "Ma103Sag", name: "材料力学基礎", type: "elective-required" },
  { code: "Md102Sag", name: "機械力学・計測制御基礎", type: "elective-required" },
  { code: "Mb201Ibg", name: "工業数学・力学１", type: "required" },
  { code: "Mb202Icg", name: "工業数学・力学２", type: "required" },
  { code: "Ma201Ibh", name: "機械設計製図１", type: "required" },
  { code: "Mz201Tbe", name: "基礎実験", type: "required" },
  { code: "Ma202Ibg", name: "材料力学１", type: "required" },
  { code: "Ma203Ibh", name: "機械設計製図２", type: "required" },
  { code: "Mz202Tce", name: "機械実験", type: "required" },
  { code: "Md201Ibg", name: "応用数学", type: "elective" },
  { code: "Mc201Ibg", name: "材料科学２", type: "elective" },
  { code: "Me201Ibg", name: "工業熱力学１", type: "elective-required" },
  { code: "Me202Ibg", name: "流体力学１", type: "elective-required" },
  { code: "Mc202Ibg", name: "機械加工", type: "elective" },
  { code: "Md202Ibg", name: "機械力学１", type: "elective-required" },
  { code: "Md203Ibg", name: "計測制御１", type: "elective-required" },
  { code: "Mb203Icg", name: "数値計算法", type: "elective" },
  { code: "Mb204Ibg", name: "機械の線形代数学", type: "elective" },
  { code: "Mb205Ibh", name: "機械のＣ言語", type: "elective" },
  { code: "Mz301Tde", name: "専門ゼミ", type: "required" },
  { code: "Mb301Idg", name: "工業数学・力学３", type: "elective" },
  { code: "Ma301Ibg", name: "材料力学２", type: "elective-required" },
  { code: "Me301Ibg", name: "流体力学２", type: "elective" },
  { code: "Me302Ibg", name: "工業熱力学２", type: "elective" },
  { code: "Ma302Ibg", name: "機械設計法", type: "elective" },
  { code: "Ma303Ibc", name: "ＣＡＤ応用", type: "elective" },
  { code: "Me303Ibg", name: "自動車工学", type: "elective" },
  { code: "Mc301Idg", name: "先端加工", type: "elective" },
  { code: "Md301Ibg", name: "機械力学２", type: "elective" },
  { code: "Md302Ibg", name: "計測制御２", type: "elective" },
  { code: "Mc302Idg", name: "生産システム", type: "elective" },
  { code: "Mc303Idg", name: "先端材料", type: "elective" },
  { code: "Me304Idg", name: "伝熱工学", type: "elective" },
  { code: "Md303Idg", name: "メカトロニクス", type: "elective" },
  { code: "Me305Idg", name: "流体機械", type: "elective" },
  { code: "Md304Idg", name: "ロボット工学", type: "elective" },
  { code: "Mc304Ibg", name: "成形加工", type: "elective" },
  { code: "Mf102Sad", name: "機械工学リテラシＡ", type: "elective" },
  { code: "Mf103Scf", name: "機械工学リテラシＢ", type: "elective" },
  { code: "Mf201Tdh", name: "機械工学プロジェクト基礎Ａ", type: "elective" },
  { code: "Mf202Tdh", name: "機械工学プロジェクト基礎Ｂ", type: "elective" },
  { code: "Mf301Tdg", name: "機械工学プロジェクト発展Ａ", type: "elective" },
  { code: "Mf302Tdh", name: "機械工学プロジェクト発展Ｂ", type: "elective" },
  { code: "Mz302Tbc", name: "卒業研究Ａ", type: "required" },
  { code: "Mz303Tde", name: "卒業研究Ｂ", type: "required" },

  // 教職用機械工学関連
  { code: "Mt101Sgh", name: "（教）工業概論", type: "elective" },
  { code: "Mt102Sag", name: "（教）職業指導１", type: "elective" },
  { code: "Mt201Seg", name: "（教）職業指導２", type: "elective" },
  { code: "Mt103Ibg", name: "（教）微分積分学１", type: "elective" },
  { code: "Mt202Ibg", name: "（教）微分積分学２", type: "elective" },
  { code: "Mt104Ibg", name: "（教）線形代数１", type: "elective" },
  { code: "Mt203Ibg", name: "（教）線形代数２", type: "elective" },
  { code: "Mt204Ibg", name: "（教）平面と空間の幾何学", type: "elective" },
  { code: "Mt105Ibg", name: "（教）確率・統計１", type: "elective" },
  { code: "Mt205Ibg", name: "（教）確率・統計２", type: "elective" },
  { code: "Mt106Ibg", name: "（教）幾何学１", type: "elective" },
  { code: "Mt206Ibg", name: "（教）幾何学２", type: "elective" },
  { code: "Mt207Igh", name: "（教）代数学", type: "elective" },
  { code: "Mt301Igh", name: "（教）フーリエ解析", type: "elective" },
  { code: "Mt302Igh", name: "（教）ベクトル解析", type: "elective" },
  { code: "Mt208Iae", name: "（教）栽培", type: "elective" },
  { code: "Mt209Sac", name: "（教）栽培実習", type: "elective" },
  { code: "Mt210Sgh", name: "（教）電気実習", type: "elective" },
  { code: "Mt211Igh", name: "（教）木材加工", type: "elective" },
  { code: "Mt212Igh", name: "（教）木材加工実習", type: "elective" },
  { code: "Mt213Igh", name: "（教）金属加工", type: "elective" },

  // 電気科目
  { code: "Ez101Iag", name: "電気数学１", type: "required" },
  { code: "Ez102Sag", name: "電気回路１", type: "required" },
  { code: "Ez103Tag", name: "電気の物理１", type: "required" },
  { code: "Ez104Iag", name: "電気数学２", type: "required" },
  { code: "Ez105Iag", name: "電気回路２", type: "required" },
  { code: "Ez106Tag", name: "電気の物理２", type: "required" },
  { code: "Ez107Sag", name: "電気計測１", type: "required" },
  { code: "Ez108Sag", name: "電気計測２", type: "required" }
];
